// <auto-generated />
using ConverterRestApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConverterRestApi.Migrations
{
    [DbContext(typeof(ConverterRestApiContext))]
    partial class ConverterRestApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConverterRestApi.Model.DataConverter", b =>
                {
                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitName");

                    b.ToTable("DataUnits");
                });

            modelBuilder.Entity("ConverterRestApi.Model.LengthConverter", b =>
                {
                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitName");

                    b.ToTable("LengthUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
